language: python

python:
  - 3.6

addons:
  apt:
    packages:
      - pyqt5-dev-tools

git:
  submodules: false

before_install:
  - git submodule update --init --recursive

install:
  - pip install -r requirements.txt

script:
  - scripts/ci/deploy.sh

env:
  global:
    - PUSH_TO=github # plugins (osgeo login, default), github (current repo)
    - PLUGIN_AUTHOR=OPENGIS.ch
