language: python

python:
  - 3.6

addons:
  apt:
    packages:
      - pyqt5-dev-tools

git:
  submodules: false

before_install:
  - git submodule update --init --recursive

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: deploy
      if: tag IS present
      script: plugin_ci/release/release.sh
